-- MySQL Script generated by MySQL Workbench
-- Sat May 19 14:46:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idUsers` INT(11) NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(15) NOT NULL,
  `Password` INT(11) NOT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`files` (
  `idTest` INT(2) NOT NULL,
  `idTask` INT(2) NOT NULL,
  `File` LONGTEXT NOT NULL,
  `Users_idUsers` INT(11) NOT NULL,
  INDEX `fk_Files_Users1_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_Files_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tests` (
  `idTests` INT(2) NOT NULL,
  `Result` VARCHAR(20) NULL,
  `Date` DATETIME NOT NULL,
  `Time` TIME(6) NOT NULL,
  `users_idUsers` INT(11) NOT NULL,
  INDEX `fk_tests_users1_idx` (`users_idUsers` ASC),
  CONSTRAINT `fk_tests_users1`
    FOREIGN KEY (`users_idUsers`)
    REFERENCES `mydb`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
